grpc:
  host: "0.0.0.0"
  port: 5001
  connect_timeout: 3
  max_pool_size: 200

http:
  host: "0.0.0.0"
  port: 8080

log:
  level: debug
  file_path: ./logs/ceramicraft-comment-mservice.log

mysql:
  host: "mysql"
  port: "3306"
  userName: "root"
  dbName: "comment_db"

mongo:
  host: "mongodb"
  port: "27017"
  database: "comment_db"

redis:
  host: "redis"
  port: 6379

audit_grpc:
  host: "ceramicraft-log-ms"
  port: 50051
