grpc:
  host: "0.0.0.0"
  port: 5001
  connect_timeout: 3
  max_pool_size: 200

http:
  host: "0.0.0.0"
  port: 8080

log:
  level: debug
  file_path: ./logs/ceramicraft-commodity-mservice.log

mysql:
  host: "mysql"
  port: "3306"
  userName: "root"
  dbName: "product_db"

s3Config:
  bucket_name: "ceramicraft"
  region: "ap-southeast-1"

kafka:
  brokers: ["kafka:9092"]
  group_id: "ceramicraft-product-group"
  max_bytes: 10485760
  commit_interval: 0

audit_grpc:
  host: "log-ms"
  port: 50051
